#!/bin/sh
#Script Name : jhincar | Made by Young-Jun Park, yjpark29@postech.ac.kr
#Description
#: Print Job History & Print INCAR tag
#Inspired by Kyung-Yeon Doh's and Hyeon Kim's jobinto Code

if [[ $# -lt 1 ]];then
    echo "Usage : jhincar [Tag1] [Tag2] ..."
    exit 0
fi

read -p "Enter the number of job history (anykey(default) = 5): " num

if [[ $num -lt 1 ]] || [[ $num == $String22 ]]
then
num=5
fi

jobid=`tail -$num  ~/a.log/input.log | tac | awk -F"." '{print $1}'`
jobaddre=`tail -$num ~/a.log/input.log | tac | awk '{print $2}'`
whattime=`tail -$num ~/a.log/input.log | tac | awk '{print "["$3"] "$4"/"$5"/"$6}' | sed -e 's/ //'`

#echo $jobid
#echo $jobaddre
#echo $whattime

echo "-------------------"
echo " [ `whoami` ]"
echo "-------------------"
#echo " Num        Date, Time         JobID                           Address"
#echo "=====||======================||=======||======================================================"
#for i in $(seq $num)
#do

#timelist=`echo $whattime | awk '{print $'"$i"'}'`
#idlist=`echo $jobid | awk '{print $'"$i"'}'`
#addlist=`echo $jobaddre | awk '{print $'"$i"'}'`

#echo " " $i  " ||" $timelist  "||"  $idlist  "||" $addlist

#done
echo "=============================================================================================="
for i in $(seq $num)
do
dir_name=`echo $jobaddre | awk '{print $'"$i"'}'`

if [ -e $dir_name/INCAR ]; then
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
for i in $@
do
grep $i $dir_name/INCAR
done
echo "-------------------------------------------------------------------------------------------"

else
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo "There is No INCAr file."
echo "-------------------------------------------------------------------------------------------"


fi


done
echo "==========================================================================================="



exit 0
~      
