#!/bin/sh
#Script Name : jhrelaxed | Made by Young-Jun Park, yjpark29@postech.ac.kr
#Description
#: Print Job History & Print relax.out (3 lines)
#Inspired by Kyung-Yeon Doh's and Hyeon Kim's jobinto Code

#if [[ $# -gt 0 ]];then
#   user=`whoami`
#   num=$1
#else
#   user=`whoami`
#   num=5
#fi


read -p "Enter the number of job history (anykey(default) = 5): " num

if [[ $num -lt 1 ]] || [[ $num == $String22 ]]
then
num=5
fi

jobid=`tail -$num  ~/a.log/input.log | tac | awk -F"." '{print $1}'`
jobaddre=`tail -$num ~/a.log/input.log | tac | awk '{print $2}'`
whattime=`tail -$num ~/a.log/input.log | tac | awk '{print "["$3"] "$4"/"$5"/"$6}' | sed -e 's/ //'`

#echo $jobid
#echo $jobaddre
#echo $whattime

echo "-------------------"
echo " [ `whoami` ]"
echo "-------------------"
#echo " Num        Date, Time         JobID                           Address"
#echo "=====||======================||=======||======================================================"
#for i in $(seq $num)
#do

#timelist=`echo $whattime | awk '{print $'"$i"'}'`
#idlist=`echo $jobid | awk '{print $'"$i"'}'`
#addlist=`echo $jobaddre | awk '{print $'"$i"'}'`

#echo " " $i  " ||" $timelist  "||"  $idlist  "||" $addlist

#done
echo "=============================================================================================="
for i in $(seq $num)
do
dir_name=`echo $jobaddre | awk '{print $'"$i"'}'`

if [ -e $dir_name/relax.out ]; then
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
tail -3 $dir_name/relax.out
echo "-------------------------------------------------------------------------------------------"

else
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo "There is No relax.out file."
echo "-------------------------------------------------------------------------------------------"

fi


done
echo "==========================================================================================="



exit 0
