#!/bin/sh
#Script Name : jobwell | Made by Young-Jun Park, yjpark29@postech.ac.kr
#Description
#: Print relax.out for the current jobs
#Inspired by Kyung-Yeon Doh's Jobaddress Code

if [[ $# -gt 0 ]];then
   user=`whoami`
   taillength=$1
else
   user=`whoami`
   taillength=1
fi

JOBS=`qstat -u $user -f`
address=`echo "$JOBS"|awk 'BEGIN{button = 0} {if( $1 == "init_work_dir" ){button=1;printf("%s",$3)} else if( $1 == "request_version" ){button=0;;printf("\n")} else if( button == 1 ){printf("%s",$1)}}'`

#echo $address | awk '{print $1}'
#echo $address | awk '{print $2}'
#echo $address | awk '{print $3}'
#echo $address | awk '{print $4}'
num_of_jobs=`echo $address | wc -w`

echo "==========================================================================================="
for i in $(seq $num_of_jobs)
do
dir_name=`echo $address | awk '{print $'"$i"'}'`

if [ -e $dir_name/relax.out ]; then
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
tail -$taillength $dir_name/relax.out
echo "-------------------------------------------------------------------------------------------"

else
echo "Directory : "$dir_name
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo "There is No relax.out file."
echo "-------------------------------------------------------------------------------------------"

fi


done
echo "==========================================================================================="
exit 0

