#!/usr/bin/env python3.9
#Script Name : trn
#Description
#: translation code
#좌표축 평행이동

import numpy as np

POSCARfile = open('POSCAR','r')

linedata=POSCARfile.readlines()

Lattice_Parameters=linedata[2:5]
coordinates=linedata[8:]

labellist=[]
LP=[]
coordi=[]

#Atom Label 추출
atom_name=linedata[5].replace('\n','').replace('\r','').split(' ')
atom_number=linedata[6].replace('\n','').replace('\r','').split(' ')
for i in range(0, len(atom_name)):
    for j in range(0,int(atom_number[i])):
        label=atom_name[i]+str(j+1)
        labellist.append(label)
        

#LP 추출
for i in range(0, len(Lattice_Parameters)):
    Lattice_Parameters[i]=Lattice_Parameters[i].replace('\n','').replace('\r','')
    LP.append(Lattice_Parameters[i].split(' '))
    
for j in range(0, len(LP)):
    LP[j] = [k for k in LP[j] if k != '']

#좌표 추출
for i in range(0, len(coordinates)):
    coordinates[i]=coordinates[i].replace('\n','').replace('\r','')
    coordi.append(coordinates[i].split(' '))
    
for j in range(0, len(coordi)):
    coordi[j] = [float(k) for k in coordi[j] if k != '']


#무게중심과 정 중앙과의 차이
for i in range(0,len(coordi)):
    print('{} : {} = {}\n'.format(i+1, labellist[i],coordi[i]))
    
user1=int(input('어떤 친구 이동할래?(number) :'))

user2=[float(input('그 친구가 이동했으면 하는 x좌표 : ')), float(input('y좌표 : ')), float(input('z좌표 : '))]

#현재 좌표와의 차이
diff=np.array(user2)-np.array(coordi[user1-1])
    
for i in range(0, len(coordi)):
    coordi[i][0]=coordi[i][0]+diff[0]
    coordi[i][1]=coordi[i][1]+diff[1]
    coordi[i][2]=coordi[i][2]+diff[2]
    
new_text_content=''
    
with open('POSCAR','r') as f:
    lines=f.readlines()
    for i, l in enumerate(lines):
        if i>=8:
            new_string='{} {} {}'.format(coordi[i-8][0], coordi[i-8][1], coordi[i-8][2])
        else:
            new_string = l.strip()
        if new_string:
            new_text_content += new_string + '\n'
        else:
            new_text_content += '\n'
            
with open('POSCAR', 'w') as f:
    f.write(new_text_content)
