#!/bin/sh

echo "*--------------------------------------------------------------------------------*"
echo "|                             <Slab Structure Maker>                             |"
echo "| o Step 1 Generate Slab Structure from Bulk Structure                           |"
echo "| o Step 2 Edit Layers of Slab Structure & Fix Bulk Layer                        |"
echo "| o Step 3 Slab Centerization & Vacuum Height re-adjustment                      |"
echo "| o Step 4 Slab Surface Area Calculator                                          |"
echo "*--------------------------------------------------------------------------------*"
read -p "몇번째 Step 을 진행할 지 정수로 적어주세요: " STEP

if [[ $STEP == 1 ]]
then
ls
python ~/SCRIPTS_PLUS/hyeon_Slab/Slab_Generator_Final.py
elif [[ $STEP == 2 ]]
then
ls
python ~/SCRIPTS_PLUS/hyeon_Slab//Slab_Editor.py

elif [[ $STEP == 3 ]]
then
ls
python ~/SCRIPTS_PLUS/hyeon_Slab//Slab_Centrize\&Vacuum_adjust.py

elif [[ $STEP == 4 ]]
then
ls
python ~/SCRIPTS_PLUS/hyeon_Slab/Slab_Surface_Area
fi

exit 0

