#!/bin/sh
read -p "Surface Area 를 구할 구조의 이름을 입력해주세요: " Structure

Uni_Con=$(sed -n "2p" $Structure)
A_Vec=($(sed -n "3p" $Structure))
B_Vec=($(sed -n "4p" $Structure))
echo "A: " ${A_Vec[@]} 
echo "B: " ${B_Vec[@]}
AA=$(echo "${A_Vec[0]}^2 + ${A_Vec[1]}^2 + ${A_Vec[2]}^2" | bc -l)
BB=$(echo "${B_Vec[0]}^2 + ${B_Vec[1]}^2 + ${B_Vec[2]}^2" | bc -l)
AB=$(echo "(${A_Vec[0]}*${B_Vec[0]} + ${A_Vec[1]}*${B_Vec[1]} + ${A_Vec[2]}*${B_Vec[2]})" |bc -l)

Surf_Area=$(echo $AA $BB $AB | awk '{print sqrt($1*$2 - $3^2)}')

echo "Surface Area of CONTCAR: " $Surf_Area "[A^2]"
