#!/bin/sh

gnuplot -persist -e "set terminal pdfcairo enhanced dashed size 6in,3in ;set output 'ping_graph2.pdf';
set bmargin 4.0;
set tmargin 1.4;
set key right top;
set border -1 lw 2;
set style line 1 lt 1 lw 5 lc rgb 'red';
set xrange [:];
set yrange [:];
set xtics font 'arial,18';
set ytics font 'arial,18';
set ylabel offset -1 font 'arial,20' \"Time\";
set xlabel offset 0 font 'arial,20' \"icmp_seq\";
set style fill transparent solid 0.2;
set tics nomirror;
plot 'ping_result27' u 7:11 w l lc rgb 'web-blue' lw 3 lt 1 title 'n027',
'ping_result28' u 7:11 w l lc rgb 'red' lw 3 lt 1 title 'n028';" # Ping

evince ping_graph2.pdf

exit 0

