#!/bin/bash
#Made by Jae-Seon Kim
#Automation by Young-Jun Park
#Total DOS Plot




system=`cat $(pwd)/run.sh | sed -n 2p | awk '{print $3}'` 
filename=`echo tdosplot_$system`

#read -p "xmin : " xmin
#read -p "xmax : " xmax
#read -p "ymin : " ymin
#read -p "ymax : " ymax

gnuplot -persist -e "set terminal pdfcairo enhanced dashed size 6in,3in ;set output '"$filename".pdf';
set bmargin 4.0;
set tmargin 1.4;
set key right top;
set border -1 lw 2;
set style line 1 lt 1 lw 5 lc rgb 'red';
set xrange [$1:$2];
set yrange [:];
set xtics font 'arial,18';
set ytics font 'arial,18';
set ylabel offset -1 font 'arial,20' \"DOS\";
set xlabel offset 0 font 'arial,20' \"Energy (eV)\";
set style fill transparent solid 0.2;
set tics nomirror;
plot 'DOS0' u 1:2 w l lc rgb 'black' lw 3 lt 1 notitle,
'DOS0' u 1:3 w l lc rgb 'web-blue' lt 1 lw 2 notitle;" # Total DOS

evince $filename.pdf
