#!/bin/bash
#Automation by Young-Jun Park
#ENCUT Convergence Test


system=`cat $(pwd)/run.sh | sed -n 2p | awk '{print $3}'` 
filename=`echo KPT_Test_$system`

#read -p "xmin : " xmin
#read -p "xmax : " xmax
#read -p "ymin : " ymin
#read -p "ymax : " ymax

gnuplot -persist -e "set terminal pdfcairo enhanced dashed size 6in,3in ;set output '"$filename".pdf';
set xlabel offset 0 font 'arial,20' 'KPT';
set ylabel offset -0.5 font 'arial,20' 'Energy Difference/atom';
set bmargin 4.0;
set tmargin 1.4;
set xtics font 'arial,18';
set ytics font 'arial,18';
set border -1 lw 2;
set style line 1 lt 1 lw 5 lc rgb 'red';
set y2label offset 0 font 'arial,20' 'time';
set y2tics font 'arial,18';
plot 'ENCUT_convtest' u 2:3 w l lc rgb 'web-blue' lw 3 lt 1 title 'dE/f.u.', 'ENCUT_convtest' u 2:7 axes x1y2 w l lc rgb 'red' lt 1 lw 2 title 'time';"

evince $filename.pdf
